name = "RAMinecraft"
author = "Carlos Lauriano"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a77b19c1eb205f73cdb7dfcf3944765dfe02409e18ab68ced4bf016efe7b1a24"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1", "1.20.2", "1.20.3", "1.20.4"]
